-- ============================================================================
-- YOLO Deals — reference data
--
-- The localities, deal types and categories every environment needs. Until
-- this migration they lived only in seed.sql, which never runs in production,
-- so a fresh production database had no categories to put a deal in.
--
-- GENERATED by scripts/gen-seed-sql.mjs --reference from src/data/seed-*.ts,
-- with the same stable ids seed.sql uses, so running both is harmless.
-- Idempotent: rows are upserted on their natural keys.
-- ============================================================================

-- ------------------------------------------------------ localities --------
insert into localities (id, name, city, centroid, aliases)
  values ('4b896204-a404-5dab-bee5-0487fa7db02a', 'Koramangala', 'Bengaluru', st_setsrid(st_makepoint(77.6245, 12.9352), 4326)::geography, array['koramangala','kormangala','kor']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('0ae06dff-8698-5ccb-8b42-0ecf32892f81', 'HSR Layout', 'Bengaluru', st_setsrid(st_makepoint(77.6474, 12.9116), 4326)::geography, array['hsr','hsr layout','hsrlayout']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('bdbc9f18-f4b0-5753-b55f-0d2c99909e61', 'Indiranagar', 'Bengaluru', st_setsrid(st_makepoint(77.6412, 12.9719), 4326)::geography, array['indiranagar','indira nagar','ingr']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('df74e82a-80e5-5f1c-9cf4-382a36b01e90', 'Jayanagar', 'Bengaluru', st_setsrid(st_makepoint(77.5938, 12.925), 4326)::geography, array['jayanagar','jaya nagar']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('45aef12f-4579-512e-a3f8-d742ed233e6f', 'Whitefield', 'Bengaluru', st_setsrid(st_makepoint(77.75, 12.9698), 4326)::geography, array['whitefield','white field']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('35ee73c3-469a-5fc6-8e8c-28673a39cd96', 'Marathahalli', 'Bengaluru', st_setsrid(st_makepoint(77.6974, 12.9591), 4326)::geography, array['marathahalli','marathalli']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('9c0cd811-b108-5032-a3ea-1e0b3d90aaaa', 'MG Road', 'Bengaluru', st_setsrid(st_makepoint(77.6068, 12.9756), 4326)::geography, array['mg road','mgroad']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('5ae4fbb0-d798-5ebe-8bf8-7cf2a3beeaf4', 'Electronic City', 'Bengaluru', st_setsrid(st_makepoint(77.6602, 12.8452), 4326)::geography, array['electronic city','ecity','e city']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('aa304895-3bd7-59fe-b63d-b571c2dc439c', 'Bellandur', 'Bengaluru', st_setsrid(st_makepoint(77.6784, 12.9304), 4326)::geography, array['bellandur']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;
insert into localities (id, name, city, centroid, aliases)
  values ('227728ae-50a2-5d5b-81b3-56cc4d17edfc', 'JP Nagar', 'Bengaluru', st_setsrid(st_makepoint(77.5857, 12.9063), 4326)::geography, array['jp nagar','jpnagar']::text[])
  on conflict (name, city) do update set centroid = excluded.centroid, aliases = excluded.aliases;

-- ------------------------------------------------------ deal types --------
insert into deal_types (code, name) values ('discount', 'Discount')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('bundle', 'Bundle')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('bxgy', 'Buy X Get Y')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('booking', 'Booking')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('experience', 'Experience')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('time_based', 'Time-based')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('flash', 'Flash Deal')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('free', 'Free')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('service_package', 'Service Package')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('property', 'Property')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('business_offer', 'Business Offer')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('transport', 'Transport')
  on conflict (code) do update set name = excluded.name;
insert into deal_types (code, name) values ('community', 'Community')
  on conflict (code) do update set name = excluded.name;

-- ------------------------------------------------------ categories --------
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('a71581d6-2d40-5436-b34e-75ffb933faaa', null, 'food', 'Food', 'food', 'utensils', '{"properties":{"cuisine":{"type":"string","title":"Cuisine","x-facet":true}}}'::jsonb, 0)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('75aa4349-43be-5a72-b837-f12b1e092cc4', null, 'retail', 'Retail', 'retail', 'bag', '{}'::jsonb, 1)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('cafe1956-7c14-531f-bce1-a88f54251413', null, 'events', 'Events', 'events', 'calendarStar', '{}'::jsonb, 2)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('0203305f-8473-5b0d-8476-4b0109a40804', null, 'mobility', 'Mobility', 'mobility', 'car', '{"properties":{"vehicle":{"type":"string","title":"Vehicle","x-facet":true}}}'::jsonb, 3)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('cda22267-fa25-5eb0-a743-cd474ddac92c', null, 'property', 'Property', 'property', 'building', '{"properties":{"bhk":{"type":"integer","title":"Size","x-facet":true,"x-label":"{value} BHK"},"furnishing":{"type":"string","title":"Furnishing","x-facet":true},"area_sqft":{"type":"integer","title":"Area (sq ft)"}}}'::jsonb, 4)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', null, 'services', 'Services', 'services', 'sparkles', '{}'::jsonb, 5)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('ae0de367-ebfd-5d58-b89c-1ea82a458bab', null, 'business', 'Business', 'business', 'briefcase', '{}'::jsonb, 6)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('c7220893-c3dc-5a11-8732-db7ff745b202', 'a71581d6-2d40-5436-b34e-75ffb933faaa', 'lunch', 'Lunch', 'food', 'restaurant-outline', '{}'::jsonb, 7)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('4836afd7-400f-5ee9-a11f-9a7cb54975a7', 'a71581d6-2d40-5436-b34e-75ffb933faaa', 'brunch', 'Brunch', 'food', 'cafe-outline', '{}'::jsonb, 8)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('3b77c2bd-2c5f-5309-9c28-bcf9fb996160', 'a71581d6-2d40-5436-b34e-75ffb933faaa', 'cafe', 'Cafe and Coffee', 'food', 'cafe-outline', '{}'::jsonb, 9)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('a36142e3-32ec-55fa-8230-b37ff468054c', 'a71581d6-2d40-5436-b34e-75ffb933faaa', 'dinner', 'Dinner', 'food', 'wine-outline', '{}'::jsonb, 10)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('eb41bbd0-4d8e-5563-8ba1-baecd6130f67', 'a71581d6-2d40-5436-b34e-75ffb933faaa', 'bar', 'Bars and Pubs', 'food', 'beer-outline', '{}'::jsonb, 11)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('fa2b3dda-c5b1-5b0b-a893-6b6e7c93ae20', '75aa4349-43be-5a72-b837-f12b1e092cc4', 'fashion', 'Fashion', 'retail', 'shirt-outline', '{}'::jsonb, 12)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('ad81dc80-dfad-5eae-b7e5-7ed516cdcf32', '75aa4349-43be-5a72-b837-f12b1e092cc4', 'electronics', 'Electronics', 'retail', 'phone-portrait-outline', '{}'::jsonb, 13)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('3fc5a364-ffe6-532e-a222-2e818897332e', '75aa4349-43be-5a72-b837-f12b1e092cc4', 'grocery', 'Grocery', 'retail', 'basket-outline', '{}'::jsonb, 14)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('5a30ccec-777a-5017-8f6c-7b70892cd230', 'cafe1956-7c14-531f-bce1-a88f54251413', 'comedy', 'Comedy and Stand-up', 'events', 'mic-outline', '{}'::jsonb, 15)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('5a6c6d9b-95cd-582d-84b9-49657dd742dd', 'cafe1956-7c14-531f-bce1-a88f54251413', 'music', 'Live Music', 'events', 'musical-notes-outline', '{}'::jsonb, 16)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('33b45660-e3a8-5351-b02f-d4a7e97b86ce', 'cafe1956-7c14-531f-bce1-a88f54251413', 'nightlife', 'Nightlife', 'events', 'moon-outline', '{}'::jsonb, 17)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('9db3e351-fc98-5e10-9b70-e28c8e44ceb3', 'cafe1956-7c14-531f-bce1-a88f54251413', 'workshop', 'Workshops', 'events', 'color-palette-outline', '{}'::jsonb, 18)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('fef09d24-c58d-5efd-9037-340f1b3ad588', 'cafe1956-7c14-531f-bce1-a88f54251413', 'classes', 'Classes', 'events', 'school-outline', '{}'::jsonb, 19)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('0a61a39f-b41f-5297-a47c-8d1dc96c0834', 'cafe1956-7c14-531f-bce1-a88f54251413', 'volunteer', 'Volunteering', 'events', 'heart-outline', '{}'::jsonb, 20)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('64ad9e3e-4db4-5ed6-82ca-b26ccbd29aad', '0203305f-8473-5b0d-8476-4b0109a40804', 'cab', 'Cabs', 'mobility', 'car-outline', '{}'::jsonb, 21)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('689ee33e-e400-55fb-bc7b-963ddfbd9d2d', '0203305f-8473-5b0d-8476-4b0109a40804', 'bike-rental', 'Bike and Scooty Rental', 'mobility', 'bicycle-outline', '{}'::jsonb, 22)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('793f6af4-5314-536c-ba3c-9c274271f017', 'cda22267-fa25-5eb0-a743-cd474ddac92c', 'rent', 'Flats', 'property', 'home-outline', '{}'::jsonb, 23)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('cec8af58-092e-5c3e-968f-5a409fab0609', 'cda22267-fa25-5eb0-a743-cd474ddac92c', 'villa', 'Villas', 'property', 'home-outline', '{}'::jsonb, 24)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('75fd42a8-2aee-5ffc-b1d0-84a3e6861938', 'cda22267-fa25-5eb0-a743-cd474ddac92c', 'coliving', 'Rooms and PG', 'property', 'bed-outline', '{}'::jsonb, 25)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('d30b25b5-863b-5fad-9101-b85aab0ea884', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'salon', 'Salon and Spa', 'services', 'cut-outline', '{}'::jsonb, 26)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('da26d6ee-c6e1-5d50-a3bf-9507d5023b61', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'makeup', 'Makeup', 'services', 'brush-outline', '{}'::jsonb, 27)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('0bec712a-cc76-53de-a48e-be7349f7d6aa', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'facials', 'Facials and Skin', 'services', 'flower-outline', '{}'::jsonb, 28)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('fe7c8a79-2fa4-5c5e-9e91-4d502fc609e3', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'cleaning', 'Home Cleaning', 'services', 'sparkles-outline', '{}'::jsonb, 29)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('366cf5ca-a19e-5838-ae61-2db18b33075a', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'repair', 'Home Repair', 'services', 'hammer-outline', '{}'::jsonb, 30)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('8785946c-77d1-52f2-9f19-9bbc370c59c2', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'fitness', 'Fitness', 'services', 'barbell-outline', '{}'::jsonb, 31)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('af6de42d-0c76-5c90-a6cb-067412a028ad', '2ab4e0c6-8d48-5e9b-86fe-a471de7cfff9', 'vehicle-care', 'Vehicle Care', 'services', 'construct-outline', '{}'::jsonb, 32)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('828982f1-a006-50e5-8435-bb550869884e', 'ae0de367-ebfd-5d58-b89c-1ea82a458bab', 'coworking', 'Coworking', 'business', 'business-outline', '{}'::jsonb, 33)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;
insert into categories (id, parent_id, slug, name, vertical, icon, attribute_schema, sort_order)
  values ('e0b3a889-11e4-5e8c-9bc8-09f5c81503b5', 'ae0de367-ebfd-5d58-b89c-1ea82a458bab', 'b2b', 'B2B Offers', 'business', 'briefcase-outline', '{}'::jsonb, 34)
  on conflict (slug) do update set name = excluded.name, icon = excluded.icon, parent_id = excluded.parent_id,
    vertical = excluded.vertical, attribute_schema = excluded.attribute_schema;

